# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            jimsey
tagline:          'A website of some sort.'
description:      'Stuff done when on the train.'
url:              http://www.jimsey.org
baseurl:          /

author:
  name:           'James Burton'
  url:            https://github.com/the-james-burton

paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/the-james-burton

soundcloud:
  url:            https://soundcloud.com/jimsey

license:
  url:            https://creativecommons.org/licenses/by/4.0
