# Site settings
title: jimsey.org
description: not doing sudoku on the train

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site

author:
  fullname: James Burton
  googleplus: https://plus.google.com/u/0/104887858566440024499
  github: the-james-burton
  soundcloud: jimsey
  linkedin: james-burton-86bb1730
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown

theme:
  author: kronik3r
  name: daktilo

license:
  url: https://creativecommons.org/licenses/by/4.0
