# Dependencies
# markdown:         redcarpet
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            jimsey
tagline:          'A website of some sort.'
description:      'Stuff done when on the train.'
url:              http://www.jimsey.org
baseurl:          /

author:
  name:           'James Burton'
  url:            https://github.com/the-james-burton

paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/the-james-burton

soundcloud:
  url:            https://soundcloud.com/jimsey

linkedin:
  url:            https://uk.linkedin.com/in/james-burton-86bb1730

license:
  url:            https://creativecommons.org/licenses/by/4.0
